<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class StoreProgramaRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'codigo' => "required|unique:programas",
            'nombre' => 'required|min:3',
            'tipo' => 'required'

        ];
    }
    public function messages()
    {
        return [
            'codigo.required' => 'El codigo es obligatorio',
            'codigo.unique' => 'El codigo es obligatorio',
            'nombre.required' => 'El nombre es obligatorio',
            'tipo.required' => 'El tipo de programa es obligatorio'

        ]; // TODO: Change the autogenerated stub
    }
}
