<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class UpdateEstudiante extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'registro' => "required|unique:estudiantes,registro,{$this->estudiante}",
            'carnet' => "required|unique:estudiantes,carnet,{$this->estudiante}",
            'nombre' => 'required|min:3',
            'apellido' => 'required',
            'sexo' => 'required|not_in:0',

            'fechanac' => 'required'
        ];
    }
    public function messages()
    {
        return [
            'registro.required' => 'El registro es obligatorio',
            'carnet.required' => 'El carnet es obligatorio',
            'registro.unique' => 'El registro ya existe'

        ]; // TODO: Change the autogenerated stub
    }
}
