<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
class UpdateDocente extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'codigo' => "required|unique:docentes,codigo,{$this->docente}",
            'carnet' => "required|unique:docentes,carnet,{$this->docente}",
            'nombre' => 'required|min:3',
            'apellido' => 'required',
            'sexo' => 'required|not_in:0',
            'grado'=> 'required',
            'fechanac' => 'required'
        ];
    }
    public function messages()
    {
        return [
            'codigo.required' => 'El codigo es obligatorio',
            'carnet.required' => 'El carnet es obligatorio',
            'codigo.unique' => 'El codigo ya existe'

        ]; // TODO: Change the autogenerated stub
    }
}
